alias cpnginx='sudo nginx -c /web/platform/config/nginx/nginx.conf'
# alias redis='redis-server /web/platform/config/redis/development.conf'
alias mysqlstart='mysql.server start'
alias mysqlstop='mysql.server stop'
# alias sunspot='rake sunspot:solr:start'
# alias sunstop='rake sunspot:solr:stop'
# alias solr='sunspot' # n00b alias
# alias cpapp='bundle exec unicorn -c /web/platform/config/unicorn/unicorn.rb -D'
# alias kill_unicorn='kill `cat /web/platform/log/unicorn_*.pid`'
# alias reapp='kill_unicorn && cpapp'
# alias resque='QUEUE=* bundle exec rake resque:work'
alias logs='tail -f /web/platform/log/*.log'
# alias rspec='bundle exec rspec --color --drb'
# alias cucumber='bundle exec cucumber --drb'
alias ci='/web/platform/build/schedule_build build --no-wait'
# alias rspec='bundle exec rspec'
# alias be='bundle exec'
# alias rake='bundle exec rake'
